// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/data/NTVDatabaseFileData.hpp"  // my header

namespace djinni_generated {

auto NTVDatabaseFileData::toCpp(const JsType& j) -> CppType {
    return {::djinni::String::Boxed::toCpp(j["name"]),
            ::djinni::I64::Boxed::toCpp(j["fileSize"]),
            ::djinni::String::Boxed::toCpp(j["filePath"])};
}
auto NTVDatabaseFileData::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("name", ::djinni::String::Boxed::fromCpp(c.name));
    js.set("fileSize", ::djinni::I64::Boxed::fromCpp(c.fileSize));
    js.set("filePath", ::djinni::String::Boxed::fromCpp(c.filePath));
    return js;
}

}  // namespace djinni_generated
