// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/data/RepositoryRows.hpp"

namespace djinni_generated {

struct NTVRepositoryRows
{
    using CppType = ::nativium::data::RepositoryRows;
    using JsType = em::val;
    using Boxed = NTVRepositoryRows;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
