// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/data/NTVRepositoryRow.hpp"  // my header

namespace djinni_generated {

auto NTVRepositoryRow::toCpp(const JsType& j) -> CppType {
    return {::djinni::List<::djinni::String>::Boxed::toCpp(j["values"])};
}
auto NTVRepositoryRow::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("values", ::djinni::List<::djinni::String>::Boxed::fromCpp(c.values));
    return js;
}

}  // namespace djinni_generated
