// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/data/NTVRepositoryTable.hpp"  // my header
#include "nativium/data/NTVRepositoryColumn.hpp"

namespace djinni_generated {

auto NTVRepositoryTable::toCpp(const JsType& j) -> CppType {
    return {::djinni::String::Boxed::toCpp(j["name"]),
            ::djinni::List<::djinni_generated::NTVRepositoryColumn>::Boxed::toCpp(j["columns"])};
}
auto NTVRepositoryTable::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("name", ::djinni::String::Boxed::fromCpp(c.name));
    js.set("columns", ::djinni::List<::djinni_generated::NTVRepositoryColumn>::Boxed::fromCpp(c.columns));
    return js;
}

}  // namespace djinni_generated
