// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/data/NTVRepositoryColumn.hpp"  // my header

namespace djinni_generated {

auto NTVRepositoryColumn::toCpp(const JsType& j) -> CppType {
    return {::djinni::I64::Boxed::toCpp(j["id"]),
            ::djinni::String::Boxed::toCpp(j["name"]),
            ::djinni::String::Boxed::toCpp(j["type"]),
            ::djinni::Bool::Boxed::toCpp(j["notNull"]),
            ::djinni::String::Boxed::toCpp(j["defaultValue"]),
            ::djinni::Bool::Boxed::toCpp(j["pk"]),
            ::djinni::String::Boxed::toCpp(j["groupType"])};
}
auto NTVRepositoryColumn::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("id", ::djinni::I64::Boxed::fromCpp(c.id));
    js.set("name", ::djinni::String::Boxed::fromCpp(c.name));
    js.set("type", ::djinni::String::Boxed::fromCpp(c.type));
    js.set("notNull", ::djinni::Bool::Boxed::fromCpp(c.notNull));
    js.set("defaultValue", ::djinni::String::Boxed::fromCpp(c.defaultValue));
    js.set("pk", ::djinni::Bool::Boxed::fromCpp(c.pk));
    js.set("groupType", ::djinni::String::Boxed::fromCpp(c.groupType));
    return js;
}

}  // namespace djinni_generated
