// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/data/RepositoryTable.hpp"

namespace djinni_generated {

struct NTVRepositoryTable
{
    using CppType = ::nativium::data::RepositoryTable;
    using JsType = em::val;
    using Boxed = NTVRepositoryTable;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
