// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/data/RepositoryColumn.hpp"

namespace djinni_generated {

struct NTVRepositoryColumn
{
    using CppType = ::nativium::data::RepositoryColumn;
    using JsType = em::val;
    using Boxed = NTVRepositoryColumn;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
