// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/data/RepositoryView.hpp"

namespace djinni_generated {

struct NTVRepositoryView
{
    using CppType = ::nativium::data::RepositoryView;
    using JsType = em::val;
    using Boxed = NTVRepositoryView;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
