// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/data/RepositoryInfo.hpp"

namespace djinni_generated {

struct NTVRepositoryInfo
{
    using CppType = ::nativium::data::RepositoryInfo;
    using JsType = em::val;
    using Boxed = NTVRepositoryInfo;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
