// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/data/NTVRepository.hpp"  // my header
#include "nativium/data/NTVRepositoryInfo.hpp"
#include "nativium/data/NTVRepositoryTable.hpp"
#include "nativium/data/NTVRepositoryView.hpp"

namespace djinni_generated {

em::val NTVRepository::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "open",
        "close",
        "test",
        "getInfo",
        "getSqliteVersion",
        "getTableList",
        "getViewList",
    });
    return methods;
}

em::val NTVRepository::shared() {
    try {
        auto r = ::nativium::data::Repository::shared();
        return ::djinni_generated::NTVRepository::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
void NTVRepository::open(const CppType& self, const std::string& w_path) {
    try {
        self->open(::djinni::String::toCpp(w_path));
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
void NTVRepository::close(const CppType& self) {
    try {
        self->close();
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
void NTVRepository::test(const CppType& self) {
    try {
        self->test();
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
em::val NTVRepository::getInfo(const CppType& self) {
    try {
        auto r = self->getInfo();
        return ::djinni_generated::NTVRepositoryInfo::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
std::string NTVRepository::getSqliteVersion(const CppType& self) {
    try {
        auto r = self->getSqliteVersion();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
em::val NTVRepository::getTableList(const CppType& self) {
    try {
        auto r = self->getTableList();
        return ::djinni::List<::djinni_generated::NTVRepositoryTable>::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}
em::val NTVRepository::getViewList(const CppType& self) {
    try {
        auto r = self->getViewList();
        return ::djinni::List<::djinni_generated::NTVRepositoryView>::fromCpp(r);
    }
    catch(const std::exception& e) {
        djinni::djinni_throw_native_exception(e);
        throw;
    }
}

EMSCRIPTEN_BINDINGS(nativium_data_repository) {
    em::class_<::nativium::data::Repository>("Repository")
        .smart_ptr<std::shared_ptr<::nativium::data::Repository>>("Repository")
        .function("nativeDestroy", &NTVRepository::nativeDestroy)
        .class_function("shared", NTVRepository::shared)
        .function("open", NTVRepository::open)
        .function("close", NTVRepository::close)
        .function("test", NTVRepository::test)
        .function("getInfo", NTVRepository::getInfo)
        .function("getSqliteVersion", NTVRepository::getSqliteVersion)
        .function("getTableList", NTVRepository::getTableList)
        .function("getViewList", NTVRepository::getViewList)
        ;
}

}  // namespace djinni_generated
