// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/data/DatabaseFileData.hpp"

namespace djinni_generated {

class NTVDatabaseFileData final {
public:
    using CppType = ::nativium::data::DatabaseFileData;
    using JniType = jobject;

    using Boxed = NTVDatabaseFileData;

    ~NTVDatabaseFileData();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NTVDatabaseFileData();
    friend ::djinni::JniClass<NTVDatabaseFileData>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nativium/data/DatabaseFileData") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;JLjava/lang/String;)V") };
    const jfieldID field_mName { ::djinni::jniGetFieldID(clazz.get(), "mName", "Ljava/lang/String;") };
    const jfieldID field_mFileSize { ::djinni::jniGetFieldID(clazz.get(), "mFileSize", "J") };
    const jfieldID field_mFilePath { ::djinni::jniGetFieldID(clazz.get(), "mFilePath", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
