// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/data/NTVDatabaseFileData.hpp"  // my header
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated {

NTVDatabaseFileData::NTVDatabaseFileData() = default;

NTVDatabaseFileData::~NTVDatabaseFileData() = default;

auto NTVDatabaseFileData::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NTVDatabaseFileData>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.name)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.fileSize)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.filePath)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NTVDatabaseFileData::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NTVDatabaseFileData>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mName)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mFileSize)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mFilePath))};
}

}  // namespace djinni_generated
