// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/data/Repository.hpp"

namespace djinni_generated {

class NTVRepository final : ::djinni::JniInterface<::nativium::data::Repository, NTVRepository> {
public:
    using CppType = std::shared_ptr<::nativium::data::Repository>;
    using CppOptType = std::shared_ptr<::nativium::data::Repository>;
    using JniType = jobject;

    using Boxed = NTVRepository;

    ~NTVRepository();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NTVRepository>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NTVRepository>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NTVRepository();
    friend ::djinni::JniClass<NTVRepository>;
    friend ::djinni::JniInterface<::nativium::data::Repository, NTVRepository>;

};

}  // namespace djinni_generated
