// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/data/NTVRepositoryTable.hpp"  // my header
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated {

NTVRepositoryTable::NTVRepositoryTable() = default;

NTVRepositoryTable::~NTVRepositoryTable() = default;

auto NTVRepositoryTable::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NTVRepositoryTable>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.name)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NTVRepositoryTable::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NTVRepositoryTable>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mName))};
}

}  // namespace djinni_generated
