// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/data/NTVRepositoryView.hpp"  // my header
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated {

NTVRepositoryView::NTVRepositoryView() = default;

NTVRepositoryView::~NTVRepositoryView() = default;

auto NTVRepositoryView::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NTVRepositoryView>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.name)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NTVRepositoryView::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NTVRepositoryView>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mName))};
}

}  // namespace djinni_generated
