// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/data/RepositoryRows.hpp"

namespace djinni_generated {

class NTVRepositoryRows final {
public:
    using CppType = ::nativium::data::RepositoryRows;
    using JniType = jobject;

    using Boxed = NTVRepositoryRows;

    ~NTVRepositoryRows();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NTVRepositoryRows();
    friend ::djinni::JniClass<NTVRepositoryRows>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nativium/data/RepositoryRows") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;I)V") };
    const jfieldID field_mList { ::djinni::jniGetFieldID(clazz.get(), "mList", "Ljava/util/ArrayList;") };
    const jfieldID field_mAmount { ::djinni::jniGetFieldID(clazz.get(), "mAmount", "I") };
};

}  // namespace djinni_generated
