// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/data/NTVRepositoryRows.hpp"  // my header
#include "com/nativium/data/NTVRepositoryRow.hpp"
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated {

NTVRepositoryRows::NTVRepositoryRows() = default;

NTVRepositoryRows::~NTVRepositoryRows() = default;

auto NTVRepositoryRows::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NTVRepositoryRows>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::List<::djinni_generated::NTVRepositoryRow>::fromCpp(jniEnv, c.list)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.amount)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NTVRepositoryRows::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NTVRepositoryRows>::get();
    return {::djinni::List<::djinni_generated::NTVRepositoryRow>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mList)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mAmount))};
}

}  // namespace djinni_generated
