// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/data/RepositoryView.hpp"

namespace djinni_generated {

class NTVRepositoryView final {
public:
    using CppType = ::nativium::data::RepositoryView;
    using JniType = jobject;

    using Boxed = NTVRepositoryView;

    ~NTVRepositoryView();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NTVRepositoryView();
    friend ::djinni::JniClass<NTVRepositoryView>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/nativium/data/RepositoryView") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;)V") };
    const jfieldID field_mName { ::djinni::jniGetFieldID(clazz.get(), "mName", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
