// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/nativium/data/NTVRepositoryColumn.hpp"  // my header
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated {

NTVRepositoryColumn::NTVRepositoryColumn() = default;

NTVRepositoryColumn::~NTVRepositoryColumn() = default;

auto NTVRepositoryColumn::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NTVRepositoryColumn>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.id)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.name)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.type)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.notNull)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.defaultValue)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.pk)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.groupType)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NTVRepositoryColumn::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 8);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NTVRepositoryColumn>::get();
    return {::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mId)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mName)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mType)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mNotNull)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mDefaultValue)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mPk)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mGroupType))};
}

}  // namespace djinni_generated
