// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>
@class NTVCoreApplicationCore;


@interface NTVCoreApplicationCore : NSObject

+ (nullable NTVCoreApplicationCore *)shared;

- (nonnull NSString *)getVersion;

- (nonnull NSString *)getEnv:(nonnull NSString *)key;

@end
