// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/core/NTVCoreApplicationCore.hpp"  // my header

namespace djinni_generated {

em::val NTVCoreApplicationCore::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getVersion",
        "getEnv",
    });
    return methods;
}

em::val NTVCoreApplicationCore::shared() {
    try {
        auto r = ::nativium::core::ApplicationCore::shared();
        return ::djinni_generated::NTVCoreApplicationCore::fromCpp(r);
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<::djinni_generated::NTVCoreApplicationCore>::handleNativeException(e);
    }
}
std::string NTVCoreApplicationCore::getVersion(const CppType& self) {
    try {
        auto r = self->getVersion();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}
std::string NTVCoreApplicationCore::getEnv(const CppType& self, const std::string& w_key) {
    try {
        auto r = self->getEnv(::djinni::String::toCpp(w_key));
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(nativium_core_application_core) {
    em::class_<::nativium::core::ApplicationCore>("ApplicationCore")
        .smart_ptr<std::shared_ptr<::nativium::core::ApplicationCore>>("ApplicationCore")
        .function("nativeDestroy", &NTVCoreApplicationCore::nativeDestroy)
        .class_function("shared", NTVCoreApplicationCore::shared)
        .function("getVersion", NTVCoreApplicationCore::getVersion)
        .function("getEnv", NTVCoreApplicationCore::getEnv)
        ;
}

}  // namespace djinni_generated
