// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni


export interface /*record*/ DatabaseFileData {
    name: string;
    fileSize: bigint;
    filePath: string;
}

export interface /*record*/ RepositoryColumn {
    id: bigint;
    name: string;
    type: string;
    notNull: boolean;
    defaultValue: string;
    pk: boolean;
    groupType: string;
}

export interface /*record*/ RepositoryRow {
    values: Array<string>;
}

export interface /*record*/ RepositoryTable {
    name: string;
}

export interface /*record*/ RepositoryView {
    name: string;
}

export interface /*record*/ RepositoryInfo {
    sqliteVersion: string;
    fileData: DatabaseFileData;
    tables: Array<RepositoryTable>;
    views: Array<RepositoryView>;
}

export interface /*record*/ RepositoryRows {
    list: Array<RepositoryRow>;
    amount: number;
}

export interface Repository {
    open(path: string): void;
    close(): void;
    test(): void;
    getInfo(): RepositoryInfo;
    getSqliteVersion(): string;
    getTableList(): Array<RepositoryTable>;
    getViewList(): Array<RepositoryView>;
    getColumns(name: string): Array<RepositoryColumn>;
    getRows(name: string, sortBy: string, descending: boolean, page: number, rowsPerPage: number): RepositoryRows;
}
export interface Repository_statics {
    shared(): Repository;
}

export interface Repository_statics {
    Repository: Repository_statics;
}
