// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni


export interface ApplicationCore {
    getVersion(): string;
    getEnv(key: string): string;
}
export interface ApplicationCore_statics {
    shared(): ApplicationCore;
}

export interface AppCore_statics {
    ApplicationCore: ApplicationCore_statics;
}
