// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

@interface NTVDatabaseFileData : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithName:(nonnull NSString *)name
                            fileSize:(int64_t)fileSize
                            filePath:(nonnull NSString *)filePath NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)databaseFileDataWithName:(nonnull NSString *)name
                                        fileSize:(int64_t)fileSize
                                        filePath:(nonnull NSString *)filePath;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly) int64_t fileSize;

@property (nonatomic, readonly, nonnull) NSString * filePath;

@end
