// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVDatabaseFileData.h"
#include "nativium/data/DatabaseFileData.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVDatabaseFileData;

namespace djinni_generated {

struct DatabaseFileData
{
    using CppType = ::nativium::data::DatabaseFileData;
    using ObjcType = NTVDatabaseFileData*;

    using Boxed = DatabaseFileData;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
