// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVDatabaseFileData+Private.h"
#import "djinni/objc/DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto DatabaseFileData::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.name),
            ::djinni::I64::toCpp(obj.fileSize),
            ::djinni::String::toCpp(obj.filePath)};
}

auto DatabaseFileData::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[NTVDatabaseFileData alloc] initWithName:(::djinni::String::fromCpp(cpp.name))
                                            fileSize:(::djinni::I64::fromCpp(cpp.fileSize))
                                            filePath:(::djinni::String::fromCpp(cpp.filePath))];
}

}  // namespace djinni_generated
