// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryInfo.h"
#include "nativium/data/RepositoryInfo.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVRepositoryInfo;

namespace djinni_generated {

struct RepositoryInfo
{
    using CppType = ::nativium::data::RepositoryInfo;
    using ObjcType = NTVRepositoryInfo*;

    using Boxed = RepositoryInfo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
