// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryRows.h"


@implementation NTVRepositoryRows

- (nonnull instancetype)initWithList:(nonnull NSArray<NTVRepositoryRow *> *)list
                              amount:(int32_t)amount
{
    if (self = [super init]) {
        _list = [list copy];
        _amount = amount;
    }
    return self;
}

+ (nonnull instancetype)repositoryRowsWithList:(nonnull NSArray<NTVRepositoryRow *> *)list
                                        amount:(int32_t)amount
{
    return [[self alloc] initWithList:list
                               amount:amount];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p list:%@ amount:%@>", self.class, (void *)self, self.list, @(self.amount)];
}

#endif
@end
