// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryRow.h"


@implementation NTVRepositoryRow

- (nonnull instancetype)initWithValues:(nonnull NSArray<NSString *> *)values
{
    if (self = [super init]) {
        _values = [values copy];
    }
    return self;
}

+ (nonnull instancetype)repositoryRowWithValues:(nonnull NSArray<NSString *> *)values
{
    return [[self alloc] initWithValues:values];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p values:%@>", self.class, (void *)self, self.values];
}

#endif
@end
