// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryTable+Private.h"
#import "djinni/objc/DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RepositoryTable::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.name)};
}

auto RepositoryTable::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[NTVRepositoryTable alloc] initWithName:(::djinni::String::fromCpp(cpp.name))];
}

}  // namespace djinni_generated
