// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryRow+Private.h"
#import "djinni/objc/DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RepositoryRow::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::List<::djinni::String>::toCpp(obj.values)};
}

auto RepositoryRow::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[NTVRepositoryRow alloc] initWithValues:(::djinni::List<::djinni::String>::fromCpp(cpp.values))];
}

}  // namespace djinni_generated
