// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryColumn.h"
#include "nativium/data/RepositoryColumn.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVRepositoryColumn;

namespace djinni_generated {

struct RepositoryColumn
{
    using CppType = ::nativium::data::RepositoryColumn;
    using ObjcType = NTVRepositoryColumn*;

    using Boxed = RepositoryColumn;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
