// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/data/Repository.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVRepository;

namespace djinni_generated {

class Repository
{
public:
    using CppType = std::shared_ptr<::nativium::data::Repository>;
    using CppOptType = std::shared_ptr<::nativium::data::Repository>;
    using ObjcType = NTVRepository*;

    using Boxed = Repository;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

