// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryTable.h"


@implementation NTVRepositoryTable

- (nonnull instancetype)initWithName:(nonnull NSString *)name
                             columns:(nonnull NSArray<NTVRepositoryColumn *> *)columns
{
    if (self = [super init]) {
        _name = [name copy];
        _columns = [columns copy];
    }
    return self;
}

+ (nonnull instancetype)repositoryTableWithName:(nonnull NSString *)name
                                        columns:(nonnull NSArray<NTVRepositoryColumn *> *)columns
{
    return [[self alloc] initWithName:name
                              columns:columns];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p name:%@ columns:%@>", self.class, (void *)self, self.name, self.columns];
}

#endif
@end
