// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryRows.h"
#include "nativium/data/RepositoryRows.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVRepositoryRows;

namespace djinni_generated {

struct RepositoryRows
{
    using CppType = ::nativium::data::RepositoryRows;
    using ObjcType = NTVRepositoryRows*;

    using Boxed = RepositoryRows;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
