// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryTable.h"


@implementation NTVRepositoryTable

- (nonnull instancetype)initWithName:(nonnull NSString *)name
{
    if (self = [super init]) {
        _name = [name copy];
    }
    return self;
}

+ (nonnull instancetype)repositoryTableWithName:(nonnull NSString *)name
{
    return [[self alloc] initWithName:name];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p name:%@>", self.class, (void *)self, self.name];
}

#endif
@end
