// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryRows+Private.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "nativium/data/NTVRepositoryRow+Private.h"
#include <cassert>

namespace djinni_generated {

auto RepositoryRows::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::List<::djinni_generated::RepositoryRow>::toCpp(obj.list),
            ::djinni::I32::toCpp(obj.amount)};
}

auto RepositoryRows::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[NTVRepositoryRows alloc] initWithList:(::djinni::List<::djinni_generated::RepositoryRow>::fromCpp(cpp.list))
                                            amount:(::djinni::I32::fromCpp(cpp.amount))];
}

}  // namespace djinni_generated
