// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryColumn.h"


@implementation NTVRepositoryColumn

- (nonnull instancetype)initWithId:(int64_t)id
                              name:(nonnull NSString *)name
                              type:(nonnull NSString *)type
                           notNull:(BOOL)notNull
                      defaultValue:(nonnull NSString *)defaultValue
                                pk:(BOOL)pk
{
    if (self = [super init]) {
        _id = id;
        _name = [name copy];
        _type = [type copy];
        _notNull = notNull;
        _defaultValue = [defaultValue copy];
        _pk = pk;
    }
    return self;
}

+ (nonnull instancetype)repositoryColumnWithId:(int64_t)id
                                          name:(nonnull NSString *)name
                                          type:(nonnull NSString *)type
                                       notNull:(BOOL)notNull
                                  defaultValue:(nonnull NSString *)defaultValue
                                            pk:(BOOL)pk
{
    return [[self alloc] initWithId:id
                               name:name
                               type:type
                            notNull:notNull
                       defaultValue:defaultValue
                                 pk:pk];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p id:%@ name:%@ type:%@ notNull:%@ defaultValue:%@ pk:%@>", self.class, (void *)self, @(self.id), self.name, self.type, @(self.notNull), self.defaultValue, @(self.pk)];
}

#endif
@end
