// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryInfo+Private.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "nativium/data/NTVDatabaseFileData+Private.h"
#import "nativium/data/NTVRepositoryTable+Private.h"
#import "nativium/data/NTVRepositoryView+Private.h"
#include <cassert>

namespace djinni_generated {

auto RepositoryInfo::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.sqliteVersion),
            ::djinni_generated::DatabaseFileData::toCpp(obj.fileData),
            ::djinni::List<::djinni_generated::RepositoryTable>::toCpp(obj.tables),
            ::djinni::List<::djinni_generated::RepositoryView>::toCpp(obj.views)};
}

auto RepositoryInfo::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[NTVRepositoryInfo alloc] initWithSqliteVersion:(::djinni::String::fromCpp(cpp.sqliteVersion))
                                                   fileData:(::djinni_generated::DatabaseFileData::fromCpp(cpp.fileData))
                                                     tables:(::djinni::List<::djinni_generated::RepositoryTable>::fromCpp(cpp.tables))
                                                      views:(::djinni::List<::djinni_generated::RepositoryView>::fromCpp(cpp.views))];
}

}  // namespace djinni_generated
