// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryColumn+Private.h"
#import "djinni/objc/DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RepositoryColumn::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.id),
            ::djinni::String::toCpp(obj.name),
            ::djinni::String::toCpp(obj.type),
            ::djinni::Bool::toCpp(obj.notNull),
            ::djinni::String::toCpp(obj.defaultValue),
            ::djinni::Bool::toCpp(obj.pk),
            ::djinni::String::toCpp(obj.groupType)};
}

auto RepositoryColumn::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[NTVRepositoryColumn alloc] initWithId:(::djinni::I64::fromCpp(cpp.id))
                                              name:(::djinni::String::fromCpp(cpp.name))
                                              type:(::djinni::String::fromCpp(cpp.type))
                                           notNull:(::djinni::Bool::fromCpp(cpp.notNull))
                                      defaultValue:(::djinni::String::fromCpp(cpp.defaultValue))
                                                pk:(::djinni::Bool::fromCpp(cpp.pk))
                                         groupType:(::djinni::String::fromCpp(cpp.groupType))];
}

}  // namespace djinni_generated
