// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

@interface NTVRepositoryRow : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithValues:(nonnull NSArray<NSString *> *)values NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)repositoryRowWithValues:(nonnull NSArray<NSString *> *)values;

@property (nonatomic, readonly, nonnull) NSArray<NSString *> * values;

@end
