// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

@interface NTVRepositoryColumn : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithId:(int64_t)id
                              name:(nonnull NSString *)name
                              type:(nonnull NSString *)type
                           notNull:(BOOL)notNull
                      defaultValue:(nonnull NSString *)defaultValue
                                pk:(BOOL)pk
                         groupType:(nonnull NSString *)groupType NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)repositoryColumnWithId:(int64_t)id
                                          name:(nonnull NSString *)name
                                          type:(nonnull NSString *)type
                                       notNull:(BOOL)notNull
                                  defaultValue:(nonnull NSString *)defaultValue
                                            pk:(BOOL)pk
                                     groupType:(nonnull NSString *)groupType;

@property (nonatomic, readonly) int64_t id;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly, nonnull) NSString * type;

@property (nonatomic, readonly) BOOL notNull;

@property (nonatomic, readonly, nonnull) NSString * defaultValue;

@property (nonatomic, readonly) BOOL pk;

@property (nonatomic, readonly, nonnull) NSString * groupType;

@end
