// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryColumn.h"
#import <Foundation/Foundation.h>

@interface NTVRepositoryTable : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithName:(nonnull NSString *)name
                             columns:(nonnull NSArray<NTVRepositoryColumn *> *)columns NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)repositoryTableWithName:(nonnull NSString *)name
                                        columns:(nonnull NSArray<NTVRepositoryColumn *> *)columns;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly, nonnull) NSArray<NTVRepositoryColumn *> * columns;

@end
