// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryTable.h"
#include "nativium/data/RepositoryTable.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVRepositoryTable;

namespace djinni_generated {

struct RepositoryTable
{
    using CppType = ::nativium::data::RepositoryTable;
    using ObjcType = NTVRepositoryTable*;

    using Boxed = RepositoryTable;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
