// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryRow.h"
#include "nativium/data/RepositoryRow.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVRepositoryRow;

namespace djinni_generated {

struct RepositoryRow
{
    using CppType = ::nativium::data::RepositoryRow;
    using ObjcType = NTVRepositoryRow*;

    using Boxed = RepositoryRow;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
