// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/data/NTVRepositoryView.h"
#include "nativium/data/RepositoryView.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NTVRepositoryView;

namespace djinni_generated {

struct RepositoryView
{
    using CppType = ::nativium::data::RepositoryView;
    using ObjcType = NTVRepositoryView*;

    using Boxed = RepositoryView;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
