// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <memory>
#include <string>

namespace nativium { namespace core {

class ApplicationCore {
public:
    virtual ~ApplicationCore() = default;

    static /*not-null*/ std::shared_ptr<ApplicationCore> shared();

    virtual std::string getVersion() = 0;

    virtual std::string getEnv(const std::string & key) = 0;
};

} }  // namespace nativium::core
