// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <string>
#include <utility>

namespace nativium { namespace data {

struct RepositoryView final {
    std::string name;

    //NOLINTNEXTLINE(google-explicit-constructor)
    RepositoryView(std::string name_)
    : name(std::move(name_))
    {}
};

} }  // namespace nativium::data
