// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <string>
#include <utility>
#include <vector>

namespace nativium { namespace data {

struct RepositoryRow final {
    std::vector<std::string> values;

    //NOLINTNEXTLINE(google-explicit-constructor)
    RepositoryRow(std::vector<std::string> values_)
    : values(std::move(values_))
    {}
};

} }  // namespace nativium::data
