// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "nativium/data/DatabaseFileData.hpp"
#include "nativium/data/RepositoryTable.hpp"
#include "nativium/data/RepositoryView.hpp"
#include <string>
#include <utility>
#include <vector>

namespace nativium { namespace data {

struct RepositoryInfo final {
    std::string sqliteVersion;
    DatabaseFileData fileData;
    std::vector<RepositoryTable> tables;
    std::vector<RepositoryView> views;

    RepositoryInfo(std::string sqliteVersion_,
                   DatabaseFileData fileData_,
                   std::vector<RepositoryTable> tables_,
                   std::vector<RepositoryView> views_)
    : sqliteVersion(std::move(sqliteVersion_))
    , fileData(std::move(fileData_))
    , tables(std::move(tables_))
    , views(std::move(views_))
    {}
};

} }  // namespace nativium::data
