// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "nativium/data/RepositoryColumn.hpp"
#include <string>
#include <utility>
#include <vector>

namespace nativium { namespace data {

struct RepositoryView final {
    std::string name;
    std::vector<RepositoryColumn> columns;

    RepositoryView(std::string name_,
                   std::vector<RepositoryColumn> columns_)
    : name(std::move(name_))
    , columns(std::move(columns_))
    {}
};

} }  // namespace nativium::data
