// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "nativium/data/RepositoryRow.hpp"
#include <cstdint>
#include <utility>
#include <vector>

namespace nativium { namespace data {

struct RepositoryRows final {
    std::vector<RepositoryRow> list;
    int32_t amount;

    RepositoryRows(std::vector<RepositoryRow> list_,
                   int32_t amount_)
    : list(std::move(list_))
    , amount(std::move(amount_))
    {}
};

} }  // namespace nativium::data
