// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace nativium { namespace data {

struct RepositoryColumn;
struct RepositoryInfo;
struct RepositoryRows;
struct RepositoryTable;
struct RepositoryView;

class Repository {
public:
    virtual ~Repository() = default;

    static /*not-null*/ std::shared_ptr<Repository> shared();

    virtual void open(const std::string & path) = 0;

    virtual void close() = 0;

    virtual void test() = 0;

    virtual RepositoryInfo getInfo() = 0;

    virtual std::string getSqliteVersion() = 0;

    virtual std::vector<RepositoryTable> getTableList() = 0;

    virtual std::vector<RepositoryView> getViewList() = 0;

    virtual std::vector<RepositoryColumn> getColumns(const std::string & name) = 0;

    virtual RepositoryRows getRows(const std::string & name, const std::string & sortBy, bool descending, int32_t page, int32_t rowsPerPage) = 0;
};

} }  // namespace nativium::data
