// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.nativium.data;

import java.util.ArrayList;

public final class RepositoryRows {


    /*package*/ final ArrayList<RepositoryRow> mList;

    /*package*/ final int mAmount;

    public RepositoryRows(
            ArrayList<RepositoryRow> list,
            int amount) {
        this.mList = list;
        this.mAmount = amount;
    }

    public ArrayList<RepositoryRow> getList() {
        return mList;
    }

    public int getAmount() {
        return mAmount;
    }

    @Override
    public String toString() {
        return "RepositoryRows{" +
                "mList=" + mList +
                "," + "mAmount=" + mAmount +
        "}";
    }

}
