// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.nativium.data;

public final class RepositoryTable {


    /*package*/ final String mName;

    public RepositoryTable(
            String name) {
        this.mName = name;
    }

    public String getName() {
        return mName;
    }

    @Override
    public String toString() {
        return "RepositoryTable{" +
                "mName=" + mName +
        "}";
    }

}
