// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.nativium.data;

import java.util.ArrayList;

public final class RepositoryRow {


    /*package*/ final ArrayList<String> mValues;

    public RepositoryRow(
            ArrayList<String> values) {
        this.mValues = values;
    }

    public ArrayList<String> getValues() {
        return mValues;
    }

    @Override
    public String toString() {
        return "RepositoryRow{" +
                "mValues=" + mValues +
        "}";
    }

}
