// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.nativium.data;

public final class RepositoryColumn {


    /*package*/ final long mId;

    /*package*/ final String mName;

    /*package*/ final String mType;

    /*package*/ final boolean mNotNull;

    /*package*/ final String mDefaultValue;

    /*package*/ final boolean mPk;

    public RepositoryColumn(
            long id,
            String name,
            String type,
            boolean notNull,
            String defaultValue,
            boolean pk) {
        this.mId = id;
        this.mName = name;
        this.mType = type;
        this.mNotNull = notNull;
        this.mDefaultValue = defaultValue;
        this.mPk = pk;
    }

    public long getId() {
        return mId;
    }

    public String getName() {
        return mName;
    }

    public String getType() {
        return mType;
    }

    public boolean getNotNull() {
        return mNotNull;
    }

    public String getDefaultValue() {
        return mDefaultValue;
    }

    public boolean getPk() {
        return mPk;
    }

    @Override
    public String toString() {
        return "RepositoryColumn{" +
                "mId=" + mId +
                "," + "mName=" + mName +
                "," + "mType=" + mType +
                "," + "mNotNull=" + mNotNull +
                "," + "mDefaultValue=" + mDefaultValue +
                "," + "mPk=" + mPk +
        "}";
    }

}
