// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.nativium.data;

import java.util.ArrayList;

public final class RepositoryView {


    /*package*/ final String mName;

    /*package*/ final ArrayList<RepositoryColumn> mColumns;

    public RepositoryView(
            String name,
            ArrayList<RepositoryColumn> columns) {
        this.mName = name;
        this.mColumns = columns;
    }

    public String getName() {
        return mName;
    }

    public ArrayList<RepositoryColumn> getColumns() {
        return mColumns;
    }

    @Override
    public String toString() {
        return "RepositoryView{" +
                "mName=" + mName +
                "," + "mColumns=" + mColumns +
        "}";
    }

}
