// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.nativium.data;

import java.util.ArrayList;

public final class RepositoryInfo {


    /*package*/ final String mSqliteVersion;

    /*package*/ final DatabaseFileData mFileData;

    /*package*/ final ArrayList<RepositoryTable> mTables;

    /*package*/ final ArrayList<RepositoryView> mViews;

    public RepositoryInfo(
            String sqliteVersion,
            DatabaseFileData fileData,
            ArrayList<RepositoryTable> tables,
            ArrayList<RepositoryView> views) {
        this.mSqliteVersion = sqliteVersion;
        this.mFileData = fileData;
        this.mTables = tables;
        this.mViews = views;
    }

    public String getSqliteVersion() {
        return mSqliteVersion;
    }

    public DatabaseFileData getFileData() {
        return mFileData;
    }

    public ArrayList<RepositoryTable> getTables() {
        return mTables;
    }

    public ArrayList<RepositoryView> getViews() {
        return mViews;
    }

    @Override
    public String toString() {
        return "RepositoryInfo{" +
                "mSqliteVersion=" + mSqliteVersion +
                "," + "mFileData=" + mFileData +
                "," + "mTables=" + mTables +
                "," + "mViews=" + mViews +
        "}";
    }

}
